import type { AdmissionRecord, University, Major, Province } from './types';

// 浙江省录取数据 (2022-2024年)
export const zhejiangAdmissions: AdmissionRecord[] = [
  // 浙江大学
  {
    id: 'zj-001',
    universityCode: '10335',
    universityName: '浙江大学',
    universityLevel: '985',
    province: 'zhejiang',
    year: 2024,
    majorName: '计算机科学与技术',
    majorCategory: '工学',
    subjectRequirement: ['physics_chemistry'],
    admissionType: 'parallel',
    lowestScore: 685,
    lowestRank: 350,
    averageScore: 688,
    highestScore: 692,
    dataSource: '浙江省教育考试院2024年普通类第一段投档线'
  },
  {
    id: 'zj-002',
    universityCode: '10335',
    universityName: '浙江大学',
    universityLevel: '985',
    province: 'zhejiang',
    year: 2024,
    majorName: '软件工程',
    majorCategory: '工学',
    subjectRequirement: ['physics_chemistry'],
    admissionType: 'parallel',
    lowestScore: 682,
    lowestRank: 420,
    averageScore: 685,
    highestScore: 689,
    dataSource: '浙江省教育考试院2024年普通类第一段投档线'
  },
  {
    id: 'zj-003',
    universityCode: '10335',
    universityName: '浙江大学',
    universityLevel: '985',
    province: 'zhejiang',
    year: 2024,
    majorName: '临床医学',
    majorCategory: '医学',
    subjectRequirement: ['chemistry_biology'],
    admissionType: 'parallel',
    lowestScore: 678,
    lowestRank: 580,
    averageScore: 681,
    highestScore: 685,
    dataSource: '浙江省教育考试院2024年普通类第一段投档线'
  },
  {
    id: 'zj-004',
    universityCode: '10335',
    universityName: '浙江大学',
    universityLevel: '985',
    province: 'zhejiang',
    year: 2024,
    majorName: '电气工程及其自动化',
    majorCategory: '工学',
    subjectRequirement: ['physics_chemistry'],
    admissionType: 'parallel',
    lowestScore: 675,
    lowestRank: 680,
    averageScore: 678,
    highestScore: 682,
    dataSource: '浙江省教育考试院2024年普通类第一段投档线'
  },
  {
    id: 'zj-005',
    universityCode: '10335',
    universityName: '浙江大学',
    universityLevel: '985',
    province: 'zhejiang',
    year: 2023,
    majorName: '计算机科学与技术',
    majorCategory: '工学',
    subjectRequirement: ['physics_chemistry'],
    admissionType: 'parallel',
    lowestScore: 683,
    lowestRank: 380,
    averageScore: 686,
    highestScore: 690,
    dataSource: '浙江省教育考试院2023年普通类第一段投档线'
  },
  // 浙江工业大学
  {
    id: 'zj-010',
    universityCode: '10337',
    universityName: '浙江工业大学',
    universityLevel: 'ordinary',
    province: 'zhejiang',
    year: 2024,
    majorName: '计算机科学与技术',
    majorCategory: '工学',
    subjectRequirement: ['physics_chemistry'],
    admissionType: 'parallel',
    lowestScore: 618,
    lowestRank: 35000,
    averageScore: 623,
    highestScore: 628,
    dataSource: '浙江省教育考试院2024年普通类第一段投档线'
  },
  {
    id: 'zj-011',
    universityCode: '10337',
    universityName: '浙江工业大学',
    universityLevel: 'ordinary',
    province: 'zhejiang',
    year: 2024,
    majorName: '软件工程',
    majorCategory: '工学',
    subjectRequirement: ['physics_chemistry'],
    admissionType: 'parallel',
    lowestScore: 615,
    lowestRank: 38000,
    averageScore: 620,
    highestScore: 625,
    dataSource: '浙江省教育考试院2024年普通类第一段投档线'
  },
  {
    id: 'zj-012',
    universityCode: '10337',
    universityName: '浙江工业大学',
    universityLevel: 'ordinary',
    province: 'zhejiang',
    year: 2024,
    majorName: '电子信息工程',
    majorCategory: '工学',
    subjectRequirement: ['physics_chemistry'],
    admissionType: 'parallel',
    lowestScore: 610,
    lowestRank: 42000,
    averageScore: 615,
    highestScore: 620,
    dataSource: '浙江省教育考试院2024年普通类第一段投档线'
  },
  {
    id: 'zj-013',
    universityCode: '10337',
    universityName: '浙江工业大学',
    universityLevel: 'ordinary',
    province: 'zhejiang',
    year: 2023,
    majorName: '计算机科学与技术',
    majorCategory: '工学',
    subjectRequirement: ['physics_chemistry'],
    admissionType: 'parallel',
    lowestScore: 615,
    lowestRank: 36800,
    averageScore: 620,
    highestScore: 625,
    dataSource: '浙江省教育考试院2023年普通类第一段投档线'
  },
  // 浙江师范大学
  {
    id: 'zj-020',
    universityCode: '10345',
    universityName: '浙江师范大学',
    universityLevel: 'ordinary',
    province: 'zhejiang',
    year: 2024,
    majorName: '汉语言文学(师范)',
    majorCategory: '文学',
    subjectRequirement: ['history_politics'],
    admissionType: 'parallel',
    lowestScore: 612,
    lowestRank: 39500,
    averageScore: 618,
    highestScore: 625,
    dataSource: '浙江省教育考试院2024年普通类第一段投档线'
  },
  {
    id: 'zj-021',
    universityCode: '10345',
    universityName: '浙江师范大学',
    universityLevel: 'ordinary',
    province: 'zhejiang',
    year: 2024,
    majorName: '数学与应用数学(师范)',
    majorCategory: '理学',
    subjectRequirement: ['physics_chemistry'],
    admissionType: 'parallel',
    lowestScore: 608,
    lowestRank: 43000,
    averageScore: 614,
    highestScore: 620,
    dataSource: '浙江省教育考试院2024年普通类第一段投档线'
  },
  {
    id: 'zj-022',
    universityCode: '10345',
    universityName: '浙江师范大学',
    universityLevel: 'ordinary',
    province: 'zhejiang',
    year: 2024,
    majorName: '英语(师范)',
    majorCategory: '文学',
    subjectRequirement: ['history_politics'],
    admissionType: 'parallel',
    lowestScore: 605,
    lowestRank: 45500,
    averageScore: 610,
    highestScore: 616,
    dataSource: '浙江省教育考试院2024年普通类第一段投档线'
  },
  // 宁波大学
  {
    id: 'zj-030',
    universityCode: '11646',
    universityName: '宁波大学',
    universityLevel: 'double_first_class',
    province: 'zhejiang',
    year: 2024,
    majorName: '计算机科学与技术',
    majorCategory: '工学',
    subjectRequirement: ['physics_chemistry'],
    admissionType: 'parallel',
    lowestScore: 605,
    lowestRank: 45800,
    averageScore: 610,
    highestScore: 615,
    dataSource: '浙江省教育考试院2024年普通类第一段投档线'
  },
  {
    id: 'zj-031',
    universityCode: '11646',
    universityName: '宁波大学',
    universityLevel: 'double_first_class',
    province: 'zhejiang',
    year: 2024,
    majorName: '法学',
    majorCategory: '法学',
    subjectRequirement: ['history_politics'],
    admissionType: 'parallel',
    lowestScore: 608,
    lowestRank: 43000,
    averageScore: 612,
    highestScore: 618,
    dataSource: '浙江省教育考试院2024年普通类第一段投档线'
  },
  {
    id: 'zj-032',
    universityCode: '11646',
    universityName: '宁波大学',
    universityLevel: 'double_first_class',
    province: 'zhejiang',
    year: 2023,
    majorName: '计算机科学与技术',
    majorCategory: '工学',
    subjectRequirement: ['physics_chemistry'],
    admissionType: 'parallel',
    lowestScore: 602,
    lowestRank: 46200,
    averageScore: 607,
    highestScore: 612,
    dataSource: '浙江省教育考试院2023年普通类第一段投档线'
  },
  // 杭州电子科技大学
  {
    id: 'zj-040',
    universityCode: '10336',
    universityName: '杭州电子科技大学',
    universityLevel: 'ordinary',
    province: 'zhejiang',
    year: 2024,
    majorName: '计算机科学与技术',
    majorCategory: '工学',
    subjectRequirement: ['physics_chemistry'],
    admissionType: 'parallel',
    lowestScore: 612,
    lowestRank: 39200,
    averageScore: 618,
    highestScore: 625,
    dataSource: '浙江省教育考试院2024年普通类第一段投档线'
  },
  {
    id: 'zj-041',
    universityCode: '10336',
    universityName: '杭州电子科技大学',
    universityLevel: 'ordinary',
    province: 'zhejiang',
    year: 2024,
    majorName: '人工智能',
    majorCategory: '工学',
    subjectRequirement: ['physics_chemistry'],
    admissionType: 'parallel',
    lowestScore: 610,
    lowestRank: 41500,
    averageScore: 616,
    highestScore: 622,
    dataSource: '浙江省教育考试院2024年普通类第一段投档线'
  },
  {
    id: 'zj-042',
    universityCode: '10336',
    universityName: '杭州电子科技大学',
    universityLevel: 'ordinary',
    province: 'zhejiang',
    year: 2024,
    majorName: '电子信息工程',
    majorCategory: '工学',
    subjectRequirement: ['physics_chemistry'],
    admissionType: 'parallel',
    lowestScore: 605,
    lowestRank: 45500,
    averageScore: 610,
    highestScore: 615,
    dataSource: '浙江省教育考试院2024年普通类第一段投档线'
  },
  // 浙江理工大学
  {
    id: 'zj-050',
    universityCode: '10338',
    universityName: '浙江理工大学',
    universityLevel: 'ordinary',
    province: 'zhejiang',
    year: 2024,
    majorName: '纺织工程',
    majorCategory: '工学',
    subjectRequirement: ['chemistry_biology'],
    admissionType: 'parallel',
    lowestScore: 575,
    lowestRank: 78000,
    averageScore: 580,
    highestScore: 585,
    dataSource: '浙江省教育考试院2024年普通类第一段投档线'
  },
  {
    id: 'zj-051',
    universityCode: '10338',
    universityName: '浙江理工大学',
    universityLevel: 'ordinary',
    province: 'zhejiang',
    year: 2024,
    majorName: '服装设计与工程',
    majorCategory: '工学',
    subjectRequirement: ['physics_chemistry'],
    admissionType: 'parallel',
    lowestScore: 580,
    lowestRank: 72000,
    averageScore: 585,
    highestScore: 590,
    dataSource: '浙江省教育考试院2024年普通类第一段投档线'
  }
];

// 山东省录取数据 (2022-2024年)
export const shandongAdmissions: AdmissionRecord[] = [
  // 山东大学
  {
    id: 'sd-001',
    universityCode: '10422',
    universityName: '山东大学',
    universityLevel: '985',
    province: 'shandong',
    year: 2024,
    majorName: '计算机科学与技术',
    majorCategory: '工学',
    subjectRequirement: ['physics_chemistry'],
    admissionType: 'parallel',
    lowestScore: 642,
    lowestRank: 5500,
    averageScore: 646,
    highestScore: 652,
    dataSource: '山东省教育招生考试院2024年普通类常规批投档线'
  },
  {
    id: 'sd-002',
    universityCode: '10422',
    universityName: '山东大学',
    universityLevel: '985',
    province: 'shandong',
    year: 2024,
    majorName: '临床医学',
    majorCategory: '医学',
    subjectRequirement: ['chemistry_biology'],
    admissionType: 'parallel',
    lowestScore: 645,
    lowestRank: 4800,
    averageScore: 650,
    highestScore: 658,
    dataSource: '山东省教育招生考试院2024年普通类常规批投档线'
  },
  {
    id: 'sd-003',
    universityCode: '10422',
    universityName: '山东大学',
    universityLevel: '985',
    province: 'shandong',
    year: 2024,
    majorName: '软件工程',
    majorCategory: '工学',
    subjectRequirement: ['physics_chemistry'],
    admissionType: 'parallel',
    lowestScore: 638,
    lowestRank: 7200,
    averageScore: 642,
    highestScore: 648,
    dataSource: '山东省教育招生考试院2024年普通类常规批投档线'
  },
  {
    id: 'sd-004',
    universityCode: '10422',
    universityName: '山东大学',
    universityLevel: '985',
    province: 'shandong',
    year: 2024,
    majorName: '法学',
    majorCategory: '法学',
    subjectRequirement: ['history_politics'],
    admissionType: 'parallel',
    lowestScore: 630,
    lowestRank: 10500,
    averageScore: 635,
    highestScore: 642,
    dataSource: '山东省教育招生考试院2024年普通类常规批投档线'
  },
  {
    id: 'sd-005',
    universityCode: '10422',
    universityName: '山东大学',
    universityLevel: '985',
    province: 'shandong',
    year: 2023,
    majorName: '计算机科学与技术',
    majorCategory: '工学',
    subjectRequirement: ['physics_chemistry'],
    admissionType: 'parallel',
    lowestScore: 640,
    lowestRank: 5800,
    averageScore: 644,
    highestScore: 650,
    dataSource: '山东省教育招生考试院2023年普通类常规批投档线'
  },
  // 中国海洋大学
  {
    id: 'sd-010',
    universityCode: '10423',
    universityName: '中国海洋大学',
    universityLevel: '985',
    province: 'shandong',
    year: 2024,
    majorName: '海洋科学',
    majorCategory: '理学',
    subjectRequirement: ['physics_chemistry'],
    admissionType: 'parallel',
    lowestScore: 615,
    lowestRank: 15500,
    averageScore: 620,
    highestScore: 628,
    dataSource: '山东省教育招生考试院2024年普通类常规批投档线'
  },
  {
    id: 'sd-011',
    universityCode: '10423',
    universityName: '中国海洋大学',
    universityLevel: '985',
    province: 'shandong',
    year: 2024,
    majorName: '计算机科学与技术',
    majorCategory: '工学',
    subjectRequirement: ['physics_chemistry'],
    admissionType: 'parallel',
    lowestScore: 622,
    lowestRank: 11800,
    averageScore: 628,
    highestScore: 635,
    dataSource: '山东省教育招生考试院2024年普通类常规批投档线'
  },
  {
    id: 'sd-012',
    universityCode: '10423',
    universityName: '中国海洋大学',
    universityLevel: '985',
    province: 'shandong',
    year: 2024,
    majorName: '食品科学与工程',
    majorCategory: '工学',
    subjectRequirement: ['chemistry_biology'],
    admissionType: 'parallel',
    lowestScore: 595,
    lowestRank: 32000,
    averageScore: 600,
    highestScore: 608,
    dataSource: '山东省教育招生考试院2024年普通类常规批投档线'
  },
  // 中国石油大学(华东)
  {
    id: 'sd-020',
    universityCode: '10425',
    universityName: '中国石油大学(华东)',
    universityLevel: '211',
    province: 'shandong',
    year: 2024,
    majorName: '石油工程',
    majorCategory: '工学',
    subjectRequirement: ['physics_chemistry'],
    admissionType: 'parallel',
    lowestScore: 598,
    lowestRank: 28500,
    averageScore: 604,
    highestScore: 612,
    dataSource: '山东省教育招生考试院2024年普通类常规批投档线'
  },
  {
    id: 'sd-021',
    universityCode: '10425',
    universityName: '中国石油大学(华东)',
    universityLevel: '211',
    province: 'shandong',
    year: 2024,
    majorName: '计算机科学与技术',
    majorCategory: '工学',
    subjectRequirement: ['physics_chemistry'],
    admissionType: 'parallel',
    lowestScore: 605,
    lowestRank: 21000,
    averageScore: 612,
    highestScore: 620,
    dataSource: '山东省教育招生考试院2024年普通类常规批投档线'
  },
  {
    id: 'sd-022',
    universityCode: '10425',
    universityName: '中国石油大学(华东)',
    universityLevel: '211',
    province: 'shandong',
    year: 2024,
    majorName: '电气工程及其自动化',
    majorCategory: '工学',
    subjectRequirement: ['physics_chemistry'],
    admissionType: 'parallel',
    lowestScore: 602,
    lowestRank: 24000,
    averageScore: 608,
    highestScore: 616,
    dataSource: '山东省教育招生考试院2024年普通类常规批投档线'
  },
  // 山东师范大学
  {
    id: 'sd-030',
    universityCode: '10445',
    universityName: '山东师范大学',
    universityLevel: 'ordinary',
    province: 'shandong',
    year: 2024,
    majorName: '汉语言文学(师范)',
    majorCategory: '文学',
    subjectRequirement: ['history_politics'],
    admissionType: 'parallel',
    lowestScore: 578,
    lowestRank: 48000,
    averageScore: 585,
    highestScore: 592,
    dataSource: '山东省教育招生考试院2024年普通类常规批投档线'
  },
  {
    id: 'sd-031',
    universityCode: '10445',
    universityName: '山东师范大学',
    universityLevel: 'ordinary',
    province: 'shandong',
    year: 2024,
    majorName: '数学与应用数学(师范)',
    majorCategory: '理学',
    subjectRequirement: ['physics_chemistry'],
    admissionType: 'parallel',
    lowestScore: 572,
    lowestRank: 55000,
    averageScore: 578,
    highestScore: 585,
    dataSource: '山东省教育招生考试院2024年普通类常规批投档线'
  },
  {
    id: 'sd-032',
    universityCode: '10445',
    universityName: '山东师范大学',
    universityLevel: 'ordinary',
    province: 'shandong',
    year: 2024,
    majorName: '心理学',
    majorCategory: '理学',
    subjectRequirement: ['physics_chemistry'],
    admissionType: 'parallel',
    lowestScore: 568,
    lowestRank: 62000,
    averageScore: 575,
    highestScore: 582,
    dataSource: '山东省教育招生考试院2024年普通类常规批投档线'
  },
  // 青岛大学
  {
    id: 'sd-040',
    universityCode: '11065',
    universityName: '青岛大学',
    universityLevel: 'ordinary',
    province: 'shandong',
    year: 2024,
    majorName: '临床医学',
    majorCategory: '医学',
    subjectRequirement: ['chemistry_biology'],
    admissionType: 'parallel',
    lowestScore: 585,
    lowestRank: 42000,
    averageScore: 592,
    highestScore: 605,
    dataSource: '山东省教育招生考试院2024年普通类常规批投档线'
  },
  {
    id: 'sd-041',
    universityCode: '11065',
    universityName: '青岛大学',
    universityLevel: 'ordinary',
    province: 'shandong',
    year: 2024,
    majorName: '计算机科学与技术',
    majorCategory: '工学',
    subjectRequirement: ['physics_chemistry'],
    admissionType: 'parallel',
    lowestScore: 575,
    lowestRank: 52000,
    averageScore: 582,
    highestScore: 590,
    dataSource: '山东省教育招生考试院2024年普通类常规批投档线'
  },
  {
    id: 'sd-042',
    universityCode: '11065',
    universityName: '青岛大学',
    universityLevel: 'ordinary',
    province: 'shandong',
    year: 2024,
    majorName: '软件工程',
    majorCategory: '工学',
    subjectRequirement: ['physics_chemistry'],
    admissionType: 'parallel',
    lowestScore: 572,
    lowestRank: 56000,
    averageScore: 578,
    highestScore: 585,
    dataSource: '山东省教育招生考试院2024年普通类常规批投档线'
  },
  // 济南大学
  {
    id: 'sd-050',
    universityCode: '10427',
    universityName: '济南大学',
    universityLevel: 'ordinary',
    province: 'shandong',
    year: 2024,
    majorName: '材料科学与工程',
    majorCategory: '工学',
    subjectRequirement: ['physics_chemistry'],
    admissionType: 'parallel',
    lowestScore: 525,
    lowestRank: 125000,
    averageScore: 532,
    highestScore: 540,
    dataSource: '山东省教育招生考试院2024年普通类常规批投档线'
  },
  {
    id: 'sd-051',
    universityCode: '10427',
    universityName: '济南大学',
    universityLevel: 'ordinary',
    province: 'shandong',
    year: 2024,
    majorName: '计算机科学与技术',
    majorCategory: '工学',
    subjectRequirement: ['physics_chemistry'],
    admissionType: 'parallel',
    lowestScore: 545,
    lowestRank: 88000,
    averageScore: 552,
    highestScore: 560,
    dataSource: '山东省教育招生考试院2024年普通类常规批投档线'
  },
  {
    id: 'sd-052',
    universityCode: '10427',
    universityName: '济南大学',
    universityLevel: 'ordinary',
    province: 'shandong',
    year: 2024,
    majorName: '会计学',
    majorCategory: '管理学',
    subjectRequirement: ['history_politics'],
    admissionType: 'parallel',
    lowestScore: 550,
    lowestRank: 82000,
    averageScore: 558,
    highestScore: 568,
    dataSource: '山东省教育招生考试院2024年普通类常规批投档线'
  }
];

// 院校基本信息
export const universities: University[] = [
  {
    code: '10335',
    name: '浙江大学',
    province: 'zhejiang',
    city: '杭州',
    level: '985',
    type: 'comprehensive',
    website: 'https://www.zju.edu.cn',
    features: ['C9联盟', '双一流', '985工程', '211工程']
  },
  {
    code: '10337',
    name: '浙江工业大学',
    province: 'zhejiang',
    city: '杭州',
    level: 'ordinary',
    type: 'engineering',
    website: 'https://www.zjut.edu.cn',
    features: ['省重点建设高校']
  },
  {
    code: '10345',
    name: '浙江师范大学',
    province: 'zhejiang',
    city: '金华',
    level: 'ordinary',
    type: 'normal',
    website: 'https://www.zjnu.edu.cn',
    features: ['省重点建设高校']
  },
  {
    code: '11646',
    name: '宁波大学',
    province: 'zhejiang',
    city: '宁波',
    level: 'double_first_class',
    type: 'comprehensive',
    website: 'https://www.nbu.edu.cn',
    features: ['双一流', '省重点建设高校']
  },
  {
    code: '10336',
    name: '杭州电子科技大学',
    province: 'zhejiang',
    city: '杭州',
    level: 'ordinary',
    type: 'engineering',
    website: 'https://www.hdu.edu.cn',
    features: ['省重点建设高校', 'IT特色鲜明']
  },
  {
    code: '10338',
    name: '浙江理工大学',
    province: 'zhejiang',
    city: '杭州',
    level: 'ordinary',
    type: 'engineering',
    website: 'https://www.zstu.edu.cn',
    features: ['省重点建设高校', '纺织特色']
  },
  {
    code: '10422',
    name: '山东大学',
    province: 'shandong',
    city: '济南',
    level: '985',
    type: 'comprehensive',
    website: 'https://www.sdu.edu.cn',
    features: ['985工程', '211工程', '双一流']
  },
  {
    code: '10423',
    name: '中国海洋大学',
    province: 'shandong',
    city: '青岛',
    level: '985',
    type: 'comprehensive',
    website: 'https://www.ouc.edu.cn',
    features: ['985工程', '211工程', '双一流', '海洋特色']
  },
  {
    code: '10425',
    name: '中国石油大学(华东)',
    province: 'shandong',
    city: '青岛',
    level: '211',
    type: 'engineering',
    website: 'https://www.upc.edu.cn',
    features: ['211工程', '双一流', '石油特色']
  },
  {
    code: '10445',
    name: '山东师范大学',
    province: 'shandong',
    city: '济南',
    level: 'ordinary',
    type: 'normal',
    website: 'https://www.sdnu.edu.cn',
    features: ['省重点建设高校']
  },
  {
    code: '11065',
    name: '青岛大学',
    province: 'shandong',
    city: '青岛',
    level: 'ordinary',
    type: 'comprehensive',
    website: 'https://www.qdu.edu.cn',
    features: ['省重点建设高校']
  },
  {
    code: '10427',
    name: '济南大学',
    province: 'shandong',
    city: '济南',
    level: 'ordinary',
    type: 'comprehensive',
    website: 'https://www.ujn.edu.cn',
    features: ['省重点建设高校']
  }
];

// 专业信息
export const majors: Major[] = [
  {
    code: '080901',
    name: '计算机科学与技术',
    category: '工学',
    employmentRate: 0.96,
    postgraduateRate: 0.35,
    salaryRange: [8000, 25000],
    description: '研究计算机系统的基础理论与应用技术，培养从事计算机软件、硬件设计与开发的高级专门人才'
  },
  {
    code: '080902',
    name: '软件工程',
    category: '工学',
    employmentRate: 0.97,
    postgraduateRate: 0.32,
    salaryRange: [9000, 28000],
    description: '研究软件开发的工程化方法，培养从事软件开发、测试、项目管理的高级专门人才'
  },
  {
    code: '080701',
    name: '电子信息工程',
    category: '工学',
    employmentRate: 0.95,
    postgraduateRate: 0.38,
    salaryRange: [7000, 22000],
    description: '研究电子设备与信息系统的设计、开发和应用，培养电子信息领域的工程技术人才'
  },
  {
    code: '080601',
    name: '电气工程及其自动化',
    category: '工学',
    employmentRate: 0.96,
    postgraduateRate: 0.30,
    salaryRange: [7000, 20000],
    description: '研究电力系统与电气设备的设计、运行和控制，培养电气工程领域的专业技术人才'
  },
  {
    code: '100201',
    name: '临床医学',
    category: '医学',
    employmentRate: 0.94,
    postgraduateRate: 0.65,
    salaryRange: [8000, 30000],
    description: '培养从事临床医疗工作的高级专门人才，学习疾病的诊断、治疗和预防'
  },
  {
    code: '050101',
    name: '汉语言文学',
    category: '文学',
    employmentRate: 0.92,
    postgraduateRate: 0.28,
    salaryRange: [5000, 15000],
    description: '研究汉语言文字及其应用，培养从事语言文字工作的高级专门人才'
  },
  {
    code: '070101',
    name: '数学与应用数学',
    category: '理学',
    employmentRate: 0.93,
    postgraduateRate: 0.40,
    salaryRange: [6000, 18000],
    description: '研究数学理论和应用方法，培养从事数学研究和应用的高级专门人才'
  },
  {
    code: '030101',
    name: '法学',
    category: '法学',
    employmentRate: 0.88,
    postgraduateRate: 0.35,
    salaryRange: [6000, 25000],
    description: '研究法律现象及其规律，培养从事法律工作的高级专门人才'
  },
  {
    code: '070701',
    name: '海洋科学',
    category: '理学',
    employmentRate: 0.90,
    postgraduateRate: 0.45,
    salaryRange: [7000, 18000],
    description: '研究海洋的自然现象、性质及其变化规律，培养海洋科学研究和技术开发人才'
  },
  {
    code: '081501',
    name: '石油工程',
    category: '工学',
    employmentRate: 0.95,
    postgraduateRate: 0.25,
    salaryRange: [8000, 22000],
    description: '研究石油和天然气勘探、开发与开采技术，培养石油工程领域的专业技术人才'
  },
  {
    code: '081701',
    name: '纺织工程',
    category: '工学',
    employmentRate: 0.94,
    postgraduateRate: 0.20,
    salaryRange: [6000, 15000],
    description: '研究纺织材料、纺织品设计及加工技术，培养纺织工程领域的专业技术人才'
  },
  {
    code: '071101',
    name: '心理学',
    category: '理学',
    employmentRate: 0.89,
    postgraduateRate: 0.42,
    salaryRange: [6000, 18000],
    description: '研究心理现象及其规律，培养从事心理学研究和应用的高级专门人才'
  },
  {
    code: '082801',
    name: '食品科学与工程',
    category: '工学',
    employmentRate: 0.93,
    postgraduateRate: 0.22,
    salaryRange: [5500, 14000],
    description: '研究食品加工、贮藏与安全控制，培养食品工程领域的专业技术人才'
  },
  {
    code: '120203',
    name: '会计学',
    category: '管理学',
    employmentRate: 0.95,
    postgraduateRate: 0.18,
    salaryRange: [5000, 16000],
    description: '研究会计理论和方法，培养从事会计、审计和财务管理的高级专门人才'
  },
  {
    code: '080717',
    name: '人工智能',
    category: '工学',
    employmentRate: 0.97,
    postgraduateRate: 0.40,
    salaryRange: [10000, 35000],
    description: '研究人工智能理论与技术，培养从事AI系统开发与应用的高级专门人才'
  }
];

// 获取指定省份的录取数据
export function getAdmissionsByProvince(province: Province): AdmissionRecord[] {
  return province === 'zhejiang' ? zhejiangAdmissions : shandongAdmissions;
}

// 根据院校代码获取院校信息
export function getUniversityByCode(code: string): University | undefined {
  return universities.find(u => u.code === code);
}

// 根据专业名称获取专业信息
export function getMajorByName(name: string): Major | undefined {
  return majors.find(m => m.name === name);
}